### ISSUE TITLE
Undefined length

### ISSUE THREAD

**Issue by nicrf** [bartmcleod/VrmlParser#10]
Hi,

I got this error with my WRL : 
`Uncaught TypeError: Cannot read property 'length' of undefined
    at k (vrml.min.js:62)
    at v (vrml.min.js:71)
    at VrmlParser.Renderer.ThreeJs.render (vrml.min.js:74)
    at Object.onLoad ((index):106)
    at XMLHttpRequest.<anonymous> (three.min.js:705)`

![2019-02-17_10h55_36](https://user-images.githubusercontent.com/29955546/52915491-acff1600-32a2-11e9-8a64-f05fdbde0155.png)

The parse is working, but the convert do not work (I use the example script) when it try to parse the scene.

**Comment by bartmcleod** [comment]
Can you provide the wrl file? You can also use the non-minified version for debugging: that should be easier.

Verstuurd vanaf mijn iPhone

**Comment by nicrf** [comment]
Hi, 

I send you an email, due to privacy of my model. I think it is the backgrounds node than throw the error.

**Comment by bartmcleod** [comment]
Thanks for the models. The issue is with the Background node, like you supected. Two properties are missing from the Background node, which are essential for rendering it: `skyAngle` and `groundAngle`. Without these properties, the converter can't know at which angles to render the changes in color. So it is not exactly a bug, although my code could give you a decent error message instead of just crashing. If you add the arrays of the angles, the Background will work.
