### ISSUE TITLE
Problem importing VrmlParser in ionic 5 project

### ISSUE THREAD

**Issue by Michael-List** [bartmcleod/VrmlParser#15]
We have successfully used the VrmlParser in our ionic 3 project: https://github.com/protolab-rosenheim/IoT_ready_App
So first of all thanks for the VrmlParser project! :)

Now I'm migrating the project to ionic 5 but the import of the file "import 'vrmlparser/vrml.js';" fails with the following message in the console:
```
Uncaught ReferenceError: vrmlParser is not defined
    at Object../node_modules/vrmlparser/vrml.js (vrml.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/three/three.component.ts (main.js:770)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/components.module.ts (app.module.ts:24)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.module.ts (app.component.ts:12)
    at __webpack_require__ (bootstrap:84)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:84)
```
I have tried different things importing the vrml.js but nothing has worked. @bartmcleod do you know what's going wrong here?

An example project can be found here: https://github.com/protolab-rosenheim/ionic-vrmlparser-test

**Comment by bartmcleod** [comment]
@Michael-list From the top of my mind I would guess that Ionic 5 is using ES6 modules. That is no coincidence, it seems to be a trend that packages are moving towards ES6. Three.js itself is now written as ES6 modules. This has caused me to start rewriting the VrmlParser project as ES6 modules as well, because I think it is important that people can use the latest and greatest Three with VrmlParser. However, that is still a work in progress. On my local repo, I have a working ES 6 version of the VrmlParser project, but it kinda works the wrong way round and I need to reverse the direction in which imports and exports go. Also, minifying and concatenating all the scripts in a single file does no longer make sense when using modules, at least, so it seems. I am not very familiar yet with ES6, so when I release it, it is likely that I will have done things in ways that are not expected by others, with more experience. So, in short, vrml.js is no ES6 module yet, so you can't use it that way. I could however push my local branch as, say, ES6 branch, so that you might be able to use that. If you only need vrml.js, then it might be easier for you to wrap it in an ES6 module and use it that way.

**Comment by Michael-List** [comment]
Thank you for your quick answer. With your hints I was able to solve the problem.

Solution:
In tsconfig.json change the line `"target": "es2015",` to `"target": "es5",`
This makes it compatible with non es2015/es6 modules.

If you release an es6 version I would be happy to test it.

Thanks for your help and best regards
Michael
