### ISSUE TITLE
Attached wrl file is not rendering

### ISSUE THREAD

**Issue by priyankatgit** [bartmcleod/VrmlParser#2]
I have attached a wrl file which is not renderig. There is no console error during vrml parsing and also parser object is returned in XHRLoader callback eventhough it is not rendering. For other files it is working but got issue in this specific file.

[bga.zip](https://github.com/bartmcleod/VrmlParser/files/538136/bga.zip)

**Comment by priyankatgit** [comment]
@bartmcleod  any comment?

**Comment by bartmcleod** [comment]
Sorry for my late reply, I apparently missed a notification from Github, should look into my mail filters.

I will look into it.

**Comment by bartmcleod** [comment]
I my first guess is that the coordIndex entries are not separated by comma's, which can be valid VRML, but might not be supported. How about the other files that do render well, do they have their coordinatie indices separated by comma's as in 

```
 coordIndex  [
    0 ,1 , 2, -1,
]
```

as opposed to

```
 coordIndex  [
    0 1  2 -1
]
```

[Edit]
I replaced them all, but that did not help, so I will have to investigate further, later today.
[Edit]
My first guess was right in so far, that the coordIndex is not being interpreted correctly. It is seen as a quaternion instead of a face index. I will check if [ 0 1 2 -1 ] is valid according to the specification. I remember this was a particularly hard part to get right in the grammar for the parser.

**Comment by bartmcleod** [comment]
If it is a lack of support of the VRML specification, I will try to build that, but I remember that these vector like things were hard.

**Comment by bartmcleod** [comment]
Ok, so I figured it out. The parser does not allow index values separated by spaces only. You also need comma's. If your exporter does not allow to export with comma's, then you can replace them in the entire file, using regex replacement. The regex I used is `((\d|e|\.|-)+)( (\d|\.|e|-)+)( (\d|\.|e|-)+)( -1)` with the replacement result `$1,$3,$5,$7,`, where $d is the matched subpattern. I used phpStorm to do the actual replacing. 

After that, the output will be valid, which can be validated with the console parser. `node vrml-parser.js`. Of course, in `vrml-parser.js`, you will have to replace `example.wrl` with `bga.wrl`.

Because the console output is hard to read and hard to search through, you may want to send the output to a file: `node vrml-parser.js > output.txt`. 

If you use the new wrl file that you get from the regex replacement to load it in the browser, you will still not see anything, because the object is _very small_. If however, you add a scale of 1000 to the first transform node in the file, you will see it:

```
DEF __1 Transform {
   scale 1000 1000 1000
```

**Comment by priyankatgit** [comment]
By replacing value as you have suggested it is working.  So I have to check if exporter allows me to expoert with comma otherwise I will use regex.
Thank you for your suggestion.

**Comment by bartmcleod** [comment]
Thanks for your feedback. I will leave the issue open for now, because I see possibilities to improve the grammar. The grammar will need awareness of what it is parsing, which it has not right now. At least, that is my current line of thought.

For example, the grammar will need to be able to distinguish between these cases in particular:
`3 2 -1` Is this a line index or a vector?
`4 3 2 -1` Is this a face index or a quaternion?

The current implementation decides as follows:
`3 2 -1` Vector
`3, 2, -1` Line index

`4 3 2 -1` Quaternion
`4, 3, 2, -1` Face index

Without knowledge of _what_ it is parsing, the grammar cannot distinguish between sequences with identical number counts, ending in -1.
