### ISSUE TITLE
Add support for text nodes

### ISSUE THREAD

**Issue by DoomTay** [bartmcleod/VrmlParser#3]
[Example file](http://hedges.org/thehedges/Ver21.wrl)

This file contains a text node with a "size" field, which for whatever reason seems to be unsupported

**Comment by bartmcleod** [comment]
The Text and FontStyle nodes are not yet supported. There is more to the file that seems to go wrong, but I will isolate the Text node as a first step, to build support for it.

**Comment by bartmcleod** [comment]
Basic Text and FontStyle node has been added in version 0.7.0.

The example file contains nodes that are defined as Anchor nodes. Anchor is not yet supported.

**Comment by bartmcleod** [comment]
@DoomTay It seems that a fix for grouped geometry that I had to introduce to add support for material on a Text node, also fixed some of the problems you experienced when trying to load your example file Ver21.wrl
<img width="1370" alt="schermafbeelding 2018-05-15 om 19 17 18" src="https://user-images.githubusercontent.com/1441397/40072809-5dd6dbec-5875-11e8-8468-866cd12e923f.png">
Could you tell me what might be missing from the scene, what is supposed to show?

**Comment by DoomTay** [comment]
Honestly, I'm not too familiar with the scene, but judging from screenshots seen [here](http://www.hedges.org/thehedges/), the eponymous hedges are supposed to be green, and there should be a blue sky. Both of those are probably unrelated to the textnodes issue, but still...

**Comment by bartmcleod** [comment]
@DoomTay Thanks for your quick reply. Textures are missing, since no images were available with the example: That's probably why the hedges aren't green. From the screenshots you linked to, it is clear that the hedges originally had a texture applied to them. The sky is blue, just not visible in the screenshot above. There are no clouds in the sky however; something that might have been accomplished with a textured box. I have an example somewhere, but did not try that one yet. Without the information, I can still work out if everything renders correctly, it will just take more time. Are you planning to revive the hedges game?

**Comment by DoomTay** [comment]
Actually, the plan is to create a browser add-on for navigating any VRML using this as a backbone, since plugins aren't exactly a thing anymore

Probably a large undertaking, and without knowledge of how VRML works, it would be even harder

**Comment by bartmcleod** [comment]
Okay... so why? Because VRML didn't really gain momentum back in the days, I think _because_ people had to install a plugin. Having to install an add-on would be very similar. I think that the great advantage of ThreeJs is that people do not need to install anything. On top of that, interacting with the VRML plugin in the old days was always a pain, because one needed an applet and the EAT. Now with javascript and Three, you can embed the VRML world and interact with it on the same page in the same language...

**Comment by DoomTay** [comment]
Hmm. I see your point. Somehow I thought that at one point VRML was much bigger.

**Comment by bartmcleod** [comment]
It was bigger than it is now, for sure.

**Comment by bartmcleod** [comment]
There's is bug in the rendering of an ImageTexture, that prevents the green of the hedges from showing, even if the texture image can be found. Although the url property is a multi-value field, a single value should be supported: `url "Green.gif"` should be valid, and it currently is not parsed correctly. I will try to fix this.

**Comment by bartmcleod** [comment]
Version 0.7.3 contains a fix for ImageTextures with an url that is just a single string, not an array of strings. The parser already handled this correctly, but the renderer assumed an array. There is no support for repeatS and repeatT yet, so repeat values (true/false) have no effect. Hence the texture is not repeated as it should, but at least the hedges are textured green now.
<img width="1424" alt="schermafbeelding 2018-05-30 om 23 48 27" src="https://user-images.githubusercontent.com/1441397/40749443-5e99fca8-6464-11e8-9c81-2b653dcd3ae8.png">

**Comment by bartmcleod** [comment]
v0.7.4 now has limited text support.
