### ISSUE TITLE
Generated VRML is not rendered as expected

### ISSUE THREAD

**Issue by swifmaneum** [bartmcleod/VrmlParser#4]
Hi there,

first of all thanks for this awesome tool :)

I'm trying to load a generated VRML file (see attachment) with your loader using the example.html, but it is not rendered like it should:

![weird](https://user-images.githubusercontent.com/7429598/38937921-a825cbec-4324-11e8-85ff-0593a573131e.PNG)

Opening the file in Windows 3D Builder shows the box correctly:

![box](https://user-images.githubusercontent.com/7429598/38937630-ee6575ea-4323-11e8-8517-0a201f93f7ac.PNG)

Do you have any clue what could be the problem here? Any insight would be highly appreciated.

[p22_test_1_simple.zip](https://github.com/bartmcleod/VrmlParser/files/1924425/p22_test_1_simple.zip)

**Comment by swifmaneum** [comment]
@bartmcleod Any idea on this one?

**Comment by bartmcleod** [comment]
@swifmaneum Thanks for posting an issue. I should do something about my GitHub notification settings, because I only saw it once you mentioned me, sorry about that. 

I am happy to look into your issue, but it might take some time.

**Comment by bartmcleod** [comment]
I imported your file into Blender and the view suggests that the shape has issues. For the VrmlParser to properly interpret the shape, there should be no mistakes in how the faces are built. The VRML examples that I use are sometimes handcoded and had similar, though less, mistakes. When I corrected those one by one, the spapes were rendered correctly. That could be an explanation of what you see. Since the shape is not overly complex, handcoding the points and faces could be a solution. Ideally, each corner of your object should have a single point only and the vertices should re-use these. Faces should be triangular and be built counter clockwise.

On the other hand, I see some properties, like _convex_, that I think the code of the VrmlParser ignores. Maybe it should not ignore this.

**Comment by swifmaneum** [comment]
Hmm thanks for your feedback! I'll turn to the company producing the VRML then. Can you point out what you mean by issues/mistakes, so I can tell them in detail what's the problem.

**Comment by bartmcleod** [comment]
Wait before slapping them around with a large trout... I have seen something in your example file that I will need to study in more detail.

**Comment by bartmcleod** [comment]
Ok, so here's the thing: Your example file has duplicate nested DEF declarations. If this sounds cryptical, here is a short explanation: In VRML, a node declared a DEF is in fact a re-usable definition and a node at the same time. So it is used where it is first declared and it is re-used wherever USE [DEFNAME] is written. So DEF names must be unique. In your file, they are not unique. To make things worse, they are nested. What happens then when parsing the definitions, the second will overwrite the first and so on. This will lead to imcompletely defined nodes. Then on each USE statement, the incomplete nodes will be resused. I think this is exactly what you are seeing: an incompletely rendered shape.

Another problem is exposed when you import the file into Blendle. You will see that the shape is not accurate. If this is intentional, then everything is fine, but from your screenshot, it seems to be far from intentional.

**Comment by bartmcleod** [comment]
I will close this now, because there is nothing I can fix based on this example, but feel free to aks any questions that remain unanswered.

**Comment by swifmaneum** [comment]
Thanks a lot for looking into this again. 

I've looked into the VRML one more time and you're right those duplicate DEFs are a problem. Also the nesting seems unnecessary sometimes. So I manually renamed the duplicate DEFs and removed some unnecessary nesting (see the attached file), but I'm still seeing the same output.

So my gut feeling is, that the structure of the file is the problem. What do you think? I'm trying to come up with a decision, if we can use the VRML parser for a project to visulize VRML files way bigger than the one we are talking about, that have a similar structure. Do you see any chance this is going to work out?

 
[ttest_1_simple_unique_defs_simplification.zip](https://github.com/bartmcleod/VrmlParser/files/1942806/ttest_1_simple_unique_defs_simplification.zip)

**Comment by bartmcleod** [comment]
If the file structure is valid it should work, if there are no other errors, such as inaccuracy or unsupported nodes. The shape is very simple, judging by your screenshot. It should be no problem to render it. If it still does not work, it might be a bug and I can work with you to fix it, so that you can use it for your project.

**Comment by bartmcleod** [comment]
Just out of curiosity: why not build the box with a single IndexedFaceSet? Why all the parts and the complex structure?

**Comment by swifmaneum** [comment]
Basically we have a piece of CAD software that generates the VRML files. As I pointed out I'll turn to the company who is responsible for this piece of software to fix the errors we discussed (duplicate DEFs, unnecessary nesting). But I guess the complex structure might be there for a reason and might not change. Anyway I'll ask them if the complex structure is necessary.

**Comment by bartmcleod** [comment]
From what I see in the file the reason could be that they want to give each surface its own texture. That might or might not be the best approach. I have only ever used simple textures myself.

I suspect the VrmlParser is doing something wrong, since Blender shows a shape that is closer to the original, than what the parser shows. So far, my research only shows that the parsers renders the specified shapes correctly, but this contradicts what we see in the overall result, so there must be something I can improve or clarify. I will keep digging.

**Comment by bartmcleod** [comment]
@swifmaneum I found that rotations like `0 2 0 1.5xxx` are causing the issue. They should be equivalent to `0 1 0 1.5xxx`, but they are not. So you definitely found a bug. You can solve it for now by changing them to `0 1 0 1.5xxx`, just as a workaround.

**Comment by bartmcleod** [comment]
Fixed in 0.6.2

**Comment by swifmaneum** [comment]
Awesome, your fix works like a charm :)
